/*
 * This file is auto-generated by a Python script.
 * DO NOT EDIT MANUALLY.
 */

#ifndef INSTRUCTION_H
#define INSTRUCTION_H

// A structure to hold RISC-V instruction data
typedef struct {
    const char* name;
    const char* long_name;
    const char* assembly;
    const char* description;
    const char* funct7;
    const char* funct3;
    const char* opcode;
} RiscVInstruction;

// Static instance containing the data from the YAML file
static const RiscVInstruction instruction_data = {
    /* name        */ "xnor",
    /* long_name   */ "Exclusive NOR",
    /* assembly    */ "xd, xs1, xs2",
    /* description */ "Performs the bit-wise exclusive-NOR operation on xs1 and xs2.",
    /* funct7      */ "0b0100000",
    /* funct3      */ "0b100",
    /* opcode      */ "0b0110011"
};

#endif // INSTRUCTION_H